require_relative 'version'
require_relative 'core_ext/numeric'
require_relative 'currencies/bitcoin'
require_relative 'currencies/ethereum'
require_relative 'currencies/indian_rupee'
require_relative 'currencies/litecoin'
