require_relative 'currencies/bitcoin'
require_relative 'currencies/ethereum'
require_relative 'currencies/indian_rupee'
require_relative 'currencies/litecoin'
require_relative 'currencies/ripple'
require_relative 'currencies/bitcoin_cash'
require_relative 'currencies/dash'
require_relative 'currencies/digibyte'
